<?php
namespace Juzdy\Http\Router\Route;

use Psr\Http\Message\ResponseFactoryInterface;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;
use Juzdy\Container\DiInvoker;
use Juzdy\Http\Router\Exception\RuntimeException;
use Juzdy\Http\Router\Route\RequestHandler\MiddlewareRequestHandler;
use Juzdy\Http\Router\Route\RequestHandler\ResolvedRouteRequestHandler;
use Juzdy\Http\Router\Contract\HasAttributes;
use Juzdy\Http\Router\Attribute\WithMiddleware;
use ReflectionAttribute;
use ReflectionClass;
use Stringable;

class Route implements RouteInterface
{
    /**
     * @var string|null The HTTP method for the route (e.g., GET, POST).
     */
    private ?string $method = null;
    /**
     * @var string|null The path pattern for the route (e.g., /users/{id}).
     */
    private ?string $path = null;
    /**
     * @var RequestHandlerInterface|callable|string|null The handler for the route, which can be a request handler instance, a callable, or a string representing a service identifier.
     */
    private $handler = null;
    /**
     * @var bool Indicates whether the route has been matched against a request.
     */
    private bool $isMatched = false;
    /**
     * @var array An array of middleware associated with the route, which can contain string identifiers or MiddlewareInterface instances.
     */
    private array $middleware = [];
    /**
     * @var array An associative array of parameters extracted from the route path when a match occurs.
     */
    private array $parameters = [];

    /**
     * @param HandlerFactory            $handlerFactory  The factory for creating route handlers.
     * @param MiddlewareFactory         $middlewareFactory The factory for creating route middleware.
     * @param ResponseFactoryInterface  $responseFactory The factory for creating response instances.
     * @param DiInvoker                 $invoker         The invoker for calling handlers and middleware with dependency injection.
     */
    public function __construct(
        private HandlerFactory $handlerFactory,
        private MiddlewareFactory $middlewareFactory,
        private ResponseFactoryInterface $responseFactory,
        private DiInvoker $invoker,
    ) 
    {}

    /**
     * {@inheritDoc}
     */
    public function matches(string $requestMethod, string $requestPath): bool
    {
        $requestPath = $this->normalizePath($requestPath);

        return $this->matchesMethod($requestMethod)
            && ($this->matchesExactPath($requestPath) || $this->matchesParameterizedPath($requestPath));
    }

    /**
     * {@inheritDoc}
     */
    public function handler(RequestHandlerInterface|callable|string $handler): static
    {
        $this->handler = $handler;
        return $this;
    }

    /**
     * {@inheritDoc}
     */
    public function path(string $path): static
    {
        $this->path = rtrim($path, '/');

        return $this;
    }

    /**
     * {@inheritDoc}
     */
    public function method(string $method): static
    {
        $this->method = strtoupper($method);
        return $this;
    }

    /**
     * {@inheritDoc}
     */
    public function withMiddleware(string|MiddlewareInterface ...$middleware): static
    {

        foreach ($middleware as $middlewareClass) {
            if (is_string($middlewareClass) && !is_a($middlewareClass, MiddlewareInterface::class, true)) {
                throw new RuntimeException("Class {$middlewareClass} does not implement MiddlewareInterface.");
            }
        }

        $this->middleware = array_merge($this->middleware, $middleware);

        return $this;
    }

    /**
     * {@inheritDoc}
     */
    public function handle(ServerRequestInterface $request): ResponseInterface
    {
        $this->assertReadyToHandle();

        $request = $this->mergeQueryParams($request);

        return $this->processWithMiddleware($request);
    }

    /**
     * Process the request through the route's middleware stack and then invoke the handler.
     *
     * @param ServerRequestInterface $request The incoming server request to process.
     * 
     * @return ResponseInterface The response generated by the handler.
     */
    protected function processWithMiddleware(ServerRequestInterface $request): ResponseInterface
    {
        return $this->createMiddlewarePipeline()->handle($request);
    }

    protected function createMiddlewarePipeline(): RequestHandlerInterface
    {
        return array_reduce(
            $this->resolveMiddlewareStack(),
            static fn (RequestHandlerInterface $next, MiddlewareInterface $middleware): RequestHandlerInterface =>
                new MiddlewareRequestHandler($middleware, $next),
            $this->createRequestHandler($this->resolveHandler()),
        );
    }

    /**
     * Resolve the configured route handler before building the middleware pipeline.
     *
     * @return RequestHandlerInterface|callable
     */
    protected function resolveHandler(): RequestHandlerInterface|callable
    {
        if (is_string($this->handler)) {
            $this->handler = $this->createHandler($this->handler);
        }

        return match (true) {
            $this->handler instanceof RequestHandlerInterface,
            is_callable($this->handler) => $this->handler,
            default => throw new RuntimeException(_("Handler is not callable or a valid request handler instance.")),
        };
    }

    /**
     * Wrap the resolved route endpoint in a RequestHandlerInterface so middleware can
     * process request handlers and callables uniformly.
     *
     * @param RequestHandlerInterface|callable $handler
     */
    protected function createRequestHandler(RequestHandlerInterface|callable $handler): RequestHandlerInterface
    {
        return new ResolvedRouteRequestHandler(
            $handler,
            $this->invoker,
            fn (mixed $response): ResponseInterface => $this->normalizeResponse($response),
        );
    }

    /**
     * Normalize a handler result into a response instance.
     */
    protected function normalizeResponse(mixed $response): ResponseInterface
    {
        return match (true) {
            $response instanceof Stringable,
            is_string($response) => $this->stringableResponse($response),
            $response instanceof ResponseInterface => $response,
            default => throw new RuntimeException(_("Invalid response type returned from middleware or handler.")),
        };
    }

    /**
     * Convert a stringable or string response into a ResponseInterface instance.
     *
     * @param Stringable|string $response The response content to convert.
     * 
     * @return ResponseInterface The created response instance with the content.
     */
    protected function stringableResponse(Stringable|string $response): ResponseInterface
    {
        //@todo: add headers, status code, etc.
        $responseInstance = $this->responseFactory->createResponse();
        $responseInstance->getBody()->write((string)$response);
        return $responseInstance;
    }

    /**
     * Get the route parameters extracted from the path.
     *
     * @return array The route parameters as an associative array.
     */
    protected function getParameters(): array
    {
        return $this->parameters;
    }

    /**
     * Merge route parameters with query parameters, ensuring no conflicts.
     *
     * @param ServerRequestInterface $request The incoming server request.
     * 
     * @return ServerRequestInterface The modified request with merged query parameters.
     * 
     * @throws RuntimeException If there are conflicting parameter names between route parameters and query parameters.
     */
    protected function mergeQueryParams(ServerRequestInterface $request): ServerRequestInterface
    {
        $queryParams = $request->getQueryParams();
        $intersection = array_intersect($this->getParameters(), $queryParams);

        if (!empty($intersection)) {
            throw new RuntimeException(_("Route parameters conflict with query parameters: " . implode(', ', array_keys($intersection))));
        }

        $mergedParams = array_merge($queryParams, $this->getParameters());

        return $request->withQueryParams($mergedParams);
    }

    /**
     * Create the route handler and apply any middleware defined via attributes.
     *
     * @return RequestHandlerInterface|callable The created handler ready to be invoked.
     */
    protected function createHandler(string $handlerClass): RequestHandlerInterface|callable
    {
        $handler = $this->handlerFactory->createHandler($handlerClass);

        $this->registerHandlerMiddleware($handler);

        return $handler;
    }

    /**
     * Resolve a middleware definition into a MiddlewareInterface instance.
     *
     * @param string|MiddlewareInterface $middleware The middleware definition to resolve.
     * 
     * @return string
     * 
     * @throws RuntimeException If the middleware definition is invalid or cannot be resolved.
     */
    protected function normalizePath(string $path): string
    {
        return rtrim($path, '/');
    }

    /**
     * Check if the route matches the HTTP method of the incoming request.
     *
     * @param string $requestMethod The HTTP method of the incoming request.
     * 
     * @return bool True if the route matches the request method, false otherwise.
     */
    protected function matchesMethod(string $requestMethod): bool
    {
        return $this->method === $requestMethod;
    }

    /**
     * Check if the route matches the request path exactly.
     *
     * @param string $requestPath The path of the incoming request.
     * 
     * @return bool True if the route matches the request path exactly, false otherwise.
     */
    protected function matchesExactPath(string $requestPath): bool
    {
        if ($this->path !== $requestPath) {
            return false;
        }

        return $this->isMatched = true;
    }

    /**
     * Check if the route matches the request path with parameterized segments.
     *
     * @param string $requestPath The path of the incoming request.
     * 
     * @return bool True if the route matches the request path with parameters, false otherwise.
     */
    protected function matchesParameterizedPath(string $requestPath): bool
    {
        $parameterNames = $this->extractParameterNames();

        if ($parameterNames === []) {
            return false;
        }

        if (!preg_match($this->buildPathRegex(), $requestPath, $parameterValues)) {
            return false;
        }

        array_shift($parameterValues);
        $this->parameters = array_combine($parameterNames, $parameterValues);

        return $this->isMatched = true;
    }

    /**
     * Check if the route has been matched against a request.
     *
     * @return array The parameter names extracted from the route path.
     */
    protected function extractParameterNames(): array
    {
        preg_match_all('/{([^}]+)}/', $this->path, $matches);

        return $matches[1] ?? [];
    }

    /**
     * Build a regular expression for matching the route path with parameterized segments.
     *
     * @return string The regular expression pattern for matching the route path.
     */
    protected function buildPathRegex(): string
    {
        return '#^' . preg_replace('/{[^}]+}/', '([^/]+)', $this->path) . '$#';
    }

    /**
     * Assert that the route is ready to handle a request, ensuring it has been matched and has a valid handler.
     *
     * @throws RuntimeException If the route is not ready to handle a request.
     */
    protected function assertReadyToHandle(): void
    {
        match (true) {
            !$this->isMatched => throw new RuntimeException('Route has not been matched yet.'),
            !$this->handler => throw new RuntimeException('No handler defined for this route.'),
            default => true,
        };
    }

    /**
     * @return array<int, MiddlewareInterface>
     */
    protected function resolveMiddlewareStack(): array
    {
        return array_map(
            fn (string|MiddlewareInterface $middleware): MiddlewareInterface => $this->resolveMiddleware($middleware),
            $this->middleware,
        );
    }

    /**
     * Create a middleware instance from a string identifier or return the instance if already a MiddlewareInterface.
     *
     * @param string|MiddlewareInterface $middleware The middleware definition to resolve.
     * 
     * @return MiddlewareInterface The resolved middleware instance.
     * 
     * @throws RuntimeException If the middleware definition is invalid or cannot be resolved.
     */
    protected function resolveMiddleware(string|MiddlewareInterface $middleware): MiddlewareInterface
    {
        return match (true) {
            is_string($middleware) => $this->middlewareFactory->createMiddleware($middleware),
            $middleware instanceof MiddlewareInterface => $middleware,
            default => throw new RuntimeException(_('Middleware must be either a string identifier or an instance of MiddlewareInterface.')),
        };
    }

    /**
     * Register middleware defined via attributes on the handler.
     *
     * @param RequestHandlerInterface|callable $handler The handler to inspect for middleware attributes.
     */
    protected function registerHandlerMiddleware(RequestHandlerInterface|callable $handler): void
    {
        if (!$handler instanceof HasAttributes) {
            return;
        }

        $reflection = new ReflectionClass($handler);
        $attributes = $reflection->getAttributes(WithMiddleware::class, ReflectionAttribute::IS_INSTANCEOF);

        foreach ($attributes as $attribute) {
            $instance = $attribute->newInstance();

            foreach ($instance->getMiddleware() as $middleware) {
                $this->withMiddleware($middleware);
            }
        }
    }
    
}