<?php
/**
 ▄▄▄
  █ J █ u z d y
   ▀▀▀
 */
namespace Juzdy\Http\Router;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;
use Juzdy\Http\Router\Route\RouteInterface;
use Juzdy\Http\Router\Proxy\GroupedRouter;

interface RouterInterface extends MiddlewareInterface
{
    /**
     * Adds middleware to the router.
     * Will be applied to all routes registered on this router // and its groups.
     *
     * @param MiddlewareInterface|string ...$middleware The middleware to add
     * @return static
     */
    public function withMiddleware(MiddlewareInterface|string ...$middleware): static;
    /**
     * Dispatches the incoming server request to the appropriate route handler and returns the response.
     *
     * @param ServerRequestInterface $request The incoming server request to dispatch
     * @return ResponseInterface|null The response generated by the matched route handler, or null if no route matches
     */
    public function dispatch(ServerRequestInterface $request): ?ResponseInterface;

    /**
     * Registers a group of routes with a common prefix and optional middleware.
     *
     * @param string $prefix The common prefix for all routes in the group
     * @param callable|null $callback An optional callback to define the routes within the group
     * @param MiddlewareInterface|string ...$middleware Optional middleware to apply to the group
     * 
     * @return static 
     */
    public function group(string $prefix = '', ?callable $callback = null, MiddlewareInterface|string ...$middleware): static;

    /**
     * Registers a GET route with the specified path and handler.
     *
     * @param string                                    $path       The path pattern for the route
     * @param RequestHandlerInterface|string|callable   $handler    The handler for the route, 
     *                                                              which can be a request handler instance,
     *                                                              a callable,
     *                                                              or a string representing a service identifier
     * 
     * @return RouteInterface
     */
    public function get(string $path, RequestHandlerInterface|string|callable $handler): RouteInterface;

    /**
     * Registers a POST route with the specified path and handler.
     *
     * @param string                                    $path       The path pattern for the route
     * @param RequestHandlerInterface|string|callable   $handler    The handler for the route
     *
     * @return RouteInterface
     */
    public function post(string $path, RequestHandlerInterface|string|callable $handler): RouteInterface;

    /**
     * Registers a PUT route with the specified path and handler.
     *
     * @param string                                    $path       The path pattern for the route
     * @param RequestHandlerInterface|string|callable   $handler    The handler for the route
     *
     * @return RouteInterface
     */
    public function put(string $path, RequestHandlerInterface|string|callable $handler): RouteInterface;

    /**
     * Registers a PATCH route with the specified path and handler.
     *
     * @param string                                    $path       The path pattern for the route
     * @param RequestHandlerInterface|string|callable   $handler    The handler for the route
     *
     * @return RouteInterface
     */
    public function patch(string $path, RequestHandlerInterface|string|callable $handler): RouteInterface;

    /**
     * Registers a DELETE route with the specified path and handler.
     *
     * @param string                                    $path       The path pattern for the route
     * @param RequestHandlerInterface|string|callable   $handler    The handler for the route
     *
     * @return RouteInterface
     */
    public function delete(string $path, RequestHandlerInterface|string|callable $handler): RouteInterface;

    /**
     * Registers a HEAD route with the specified path and handler.
     *
     * @param string                                    $path       The path pattern for the route
     * @param RequestHandlerInterface|string|callable   $handler    The handler for the route
     *
     * @return RouteInterface
     */
    public function head(string $path, RequestHandlerInterface|string|callable $handler): RouteInterface;

    /**
     * Registers an OPTIONS route with the specified path and handler.
     *
     * @param string                                    $path       The path pattern for the route
     * @param RequestHandlerInterface|string|callable   $handler    The handler for the route
     *
     * @return RouteInterface
     */
    public function options(string $path, RequestHandlerInterface|string|callable $handler): RouteInterface;

    //public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface;
}